server:
  port: 8080
  servlet:
    context-path: /leave
  tomcat:
    uri-encoding: UTF-8

spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  thymeleaf:
    cache: false
  datasource:
    name: test
    url: jdbc:mysql://106.13.47.126:3306/test2?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: x5zrqj@RZWD
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.student.leave.model
